### ISSUE TITLE
Fix: replace deprecated jpype.isJVMStarted() for JPype 1.6.0+ compatibility

### ISSUE THREAD

**Issue by HenryNebula** [HenryNebula/jaydebeapiarrow#47]
## Legacy Issue

baztian/jaydebeapi#253: Compatibility issues for Jaydebeapi 1.2.3 with JPype 1.6.0 and Python 3.12

## Legacy Bug

JPype 1.6.0 removed `jpype.isJVMStarted()`, causing:
```
AttributeError: module jpype has no attribute 'isJVMStarted'
```

Our codebase uses `jpype.isJVMStarted()` in three places:
- `jaydebeapiarrow/__init__.py:62` (set_debug)
- `jaydebeapiarrow/__init__.py:115` (_jdbc_connect_jpype)  
- `jaydebeapiarrow/__init__.py:247` (close)

## Expected Behavior

Connection and JVM lifecycle management should work with JPype 1.6.0+.

## Fix

Replace `jpype.isJVMStarted()` with a compatible alternative:
- Use `jpype.JVM.isStarted()` (available since JPype 1.5.0) with a fallback to the legacy API
- Or use a try/except wrapper for backward compatibility

**Comment by HenryNebula** [comment]
Triage fix: https://github.com/HenryNebula/jaydebeapiarrow/pull/48
